[build-system]
requires = [
    "conan>=2.0.0",
    "setuptools",
    "scikit-build>=0.17.3",
    "skbuild_conan@git+https://github.com/d-krupke/skbuild-conan.git",
    "cmake>=3.23",
    "ninja",
]
build-backend = "setuptools.build_meta"